cmake_minimum_required(VERSION 3.16)
project(act_lab_mujoco_system)
find_package(ament_cmake REQUIRED)
find_package(controller_manager REQUIRED)
find_package(hardware_interface REQUIRED)
find_package(pluginlib REQUIRED)
find_package(rclcpp REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(nlohmann_json REQUIRED)
add_library(act_lab_mujoco_system SHARED src/system.cpp)
target_compile_features(act_lab_mujoco_system PUBLIC cxx_std_17)
ament_target_dependencies(act_lab_mujoco_system hardware_interface pluginlib rclcpp)
pluginlib_export_plugin_description_file(hardware_interface system.xml)
add_executable(act_lab_controller src/controller.cpp)
target_compile_features(act_lab_controller PRIVATE cxx_std_17)
ament_target_dependencies(act_lab_controller controller_manager hardware_interface rclcpp geometry_msgs)
target_link_libraries(act_lab_controller act_lab_mujoco_system nlohmann_json::nlohmann_json)
install(TARGETS act_lab_mujoco_system LIBRARY DESTINATION lib)
install(TARGETS act_lab_controller DESTINATION lib/${PROJECT_NAME})
add_executable(check_system src/check_system.cpp)
target_compile_features(check_system PRIVATE cxx_std_17)
ament_target_dependencies(check_system hardware_interface rclcpp)
target_link_libraries(check_system act_lab_mujoco_system)
install(TARGETS check_system DESTINATION lib/${PROJECT_NAME})

ament_package()
